site_name: Jeff's Algorithm and Leetcode Notes

theme:
  name: material
  features:
    - navigation.sections
    # - navigation.expand

nav:
  - INTRO: index.md
  - Common:
    - Leetcode Interview 150: leetcode_interview_150.md
  - Machine Learning:
    - Common: ML/index.md

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css